package com.edurda77.impuls.tele_tv.resources.theme

import androidx.compose.ui.graphics.Color

val primaryDarkMediumContrast = Color(0xFFA6E6FF)
val onPrimaryDarkMediumContrast = Color(0xFF002A35)
val primaryContainerDarkMediumContrast = Color(0xFF509AB4)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFC9E0EB)
val onSecondaryDarkMediumContrast = Color(0xFF122830)
val secondaryContainerDarkMediumContrast = Color(0xFF7E949E)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD9D9FF)
val onTertiaryDarkMediumContrast = Color(0xFF212341)
val tertiaryContainerDarkMediumContrast = Color(0xFF8D8EB3)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1416)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E6)
val surfaceDarkMediumContrast = Color(0xFF0F1416)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF40484C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD5DEE2)
val outlineDarkMediumContrast = Color(0xFFABB3B7)
val outlineVariantDarkMediumContrast = Color(0xFF899296)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E6)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2D)
val inversePrimaryDarkMediumContrast = Color(0xFF004F62)
val surfaceDimDarkMediumContrast = Color(0xFF0F1416)
val surfaceBrightDarkMediumContrast = Color(0xFF404548)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080A)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191E21)
val surfaceContainerDarkMediumContrast = Color(0xFF23292B)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3336)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393E41)

